modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = ""
license = "MIT License"

[[mods]]
    modId = "silkablooie"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:tnt"
    authors = "DavigJ"
    credits = "DavigJ"
    displayName = "Silkablooie"
    description = '''
    Eat your heart out, minimalism.
    '''

[[dependencies.silkablooie]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.silkablooie]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"